# Generated by Django 5.0.4 on 2024-07-09 07:19

import Inlingua_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameOfCounselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelsAndHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=5)),
                ('help_text', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(default=Inlingua_app.models.generate_customer_id, max_length=20, unique=True)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Phone_No', models.CharField(max_length=100)),
                ('Student_Mail_Id', models.CharField(max_length=100)),
                ('Student_Date_of_Birth', models.DateField(blank=True, null=True)),
                ('Identity_Card_Aadhar_Copy', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Students_data)),
                ('Student_Photo', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Students_data)),
                ('Course_Type', models.CharField(choices=[('Week Days', 'Week Days'), ('Week End', 'Week End')], max_length=20)),
                ('Payment_Type', models.CharField(choices=[('Full', 'Full'), ('Part', 'Part')], max_length=20)),
                ('Transaction_ID', models.IntegerField()),
                ('Account_Holder_Name', models.CharField(max_length=100)),
                ('Account_Paide', models.FloatField()),
                ('Created_by', models.CharField(max_length=100)),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Updated_date', models.DateTimeField(auto_now=True)),
                ('Language_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.language')),
                ('Level_and_Hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.levelsandhour')),
                ('Student_Counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.nameofcounselor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
