# Generated by Django 5.0.4 on 2024-07-29 05:02

import Inlingua_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='batch_preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_preferences', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BatchTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(max_length=20)),
                ('batch_preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.batch_preferences')),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.CharField(default=Inlingua_app.models.generate_employee_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('employee_photo', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Employee_data)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Employee_data)),
                ('address', models.TextField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('bank_account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_ifsc', models.CharField(max_length=11)),
                ('passbook', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Employee_data)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_business_manager', models.BooleanField(default=False)),
                ('is_trainer_head', models.BooleanField(default=False)),
                ('is_accoountant', models.BooleanField(default=False)),
                ('is_business_development_executive', models.BooleanField(default=False)),
                ('current_role', models.CharField(choices=[('isadmin', 'Admin'), ('isbusinessmanager', 'Business Manager (BM)'), ('rainerhead', 'Trainer Head (TD)'), ('isaccountant', 'Accountant (AC)'), ('businessdevelopment', 'Business Development Executive (BDE)')], max_length=40)),
                ('Created_date', models.DateTimeField()),
                ('Updated_date', models.DateTimeField(blank=True, null=True)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_created_by', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelsAndHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=5)),
                ('hours', models.IntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='NameOfCounselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselors_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselors_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(default=Inlingua_app.models.generate_customer_id, max_length=20, unique=True)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Phone_No', models.CharField(max_length=100)),
                ('Student_Mail_Id', models.CharField(max_length=100)),
                ('Student_Date_of_Birth', models.DateField(blank=True, null=True)),
                ('Identity_Card_Aadhar_Copy', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Students_data)),
                ('Student_Photo', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Students_data)),
                ('Batch_type', models.CharField(choices=[('One to One', 'One to One'), ('Group', 'Group')], max_length=20)),
                ('Profession', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee'), ('Self Employee', 'Self Employee'), ('Others', 'Others')], max_length=20)),
                ('Payment_Type', models.CharField(choices=[('Full', 'Full'), ('Part', 'Part')], max_length=20)),
                ('Transaction_ID', models.IntegerField()),
                ('Account_Holder_Name', models.CharField(max_length=100)),
                ('Amount_Paide', models.FloatField(default=0)),
                ('Balance_Amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('New Student', 'New Student'), ('Verified', 'Verified'), ('Batch Allocated', 'Batch Allocated'), ('Waiting for Assessment', 'Waiting for Assessment'), ('Course Completed', 'Course Completed')], max_length=25)),
                ('payment_complited', models.BooleanField(default=False)),
                ('Created_date', models.DateTimeField()),
                ('Updated_date', models.DateTimeField(blank=True, null=True)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created_by', to=settings.AUTH_USER_MODEL)),
                ('Language_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.language')),
                ('Level_and_Hour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.levelsandhour')),
                ('Student_Counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.nameofcounselor')),
                ('batch_preferences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.batch_preferences')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer_ID', models.CharField(default=Inlingua_app.models.generate_trainer_id, max_length=20, unique=True)),
                ('trainer_name', models.CharField(max_length=100)),
                ('trainer_dob', models.DateField()),
                ('trainer_mail', models.EmailField(max_length=254)),
                ('trainer_phone', models.CharField(max_length=15)),
                ('trainer_address', models.TextField(max_length=500)),
                ('trainer_photo', models.FileField(upload_to=Inlingua_app.models.Trainer_data)),
                ('trainer_aadhar', models.FileField(upload_to=Inlingua_app.models.Trainer_data)),
                ('qualification', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year_of_passing', models.CharField(max_length=4)),
                ('bank_account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_ifsc', models.CharField(max_length=11)),
                ('passbook', models.FileField(upload_to=Inlingua_app.models.Trainer_data)),
                ('Created_date', models.DateTimeField()),
                ('Updated_date', models.DateTimeField(blank=True, null=True)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers_created_by', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainers_updated_by', to=settings.AUTH_USER_MODEL)),
                ('trainer_languages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_Trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=20, unique=True)),
                ('course_start_date', models.DateField(blank=True, null=True)),
                ('course_End_date', models.DateField(blank=True, null=True)),
                ('Created_date', models.DateTimeField()),
                ('Updated_date', models.DateTimeField(blank=True, null=True)),
                ('Created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_created_by', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_updated_by', to=settings.AUTH_USER_MODEL)),
                ('batch_preferences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.batch_preferences')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.batchtiming')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.language')),
                ('levels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.levelsandhour')),
                ('students', models.ManyToManyField(to='Inlingua_app.studenttable')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inlingua_app.trainertable')),
            ],
        ),
    ]
