# Generated by Django 5.0.4 on 2024-07-18 06:52

import Inlingua_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.CharField(default=Inlingua_app.models.generate_employee_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('employee_photo', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Employee_data)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Employee_data)),
                ('address', models.TextField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('bank_account_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_ifsc', models.CharField(max_length=11)),
                ('passbook', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Employee_data)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_business_manager', models.BooleanField(default=False)),
                ('is_trainer_head', models.BooleanField(default=False)),
                ('is_trainer', models.BooleanField(default=False)),
                ('is_accoountant', models.BooleanField(default=False)),
                ('is_business_development_executive', models.BooleanField(default=False)),
                ('Created_date', models.DateTimeField()),
                ('Updated_date', models.DateTimeField()),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_created_by', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_updated_by', to=settings.AUTH_USER_MODEL)),
                ('current_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.currentrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelsAndHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=5)),
                ('help_text', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels_and_hours_created_by', to='Inlingua_app.employees')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.language')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels_and_hours_updated_by', to='Inlingua_app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='NameOfCounselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselors_created_by', to='Inlingua_app.employees')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselors_updated_by', to='Inlingua_app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(default=Inlingua_app.models.generate_customer_id, max_length=20, unique=True)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Phone_No', models.CharField(max_length=100)),
                ('Student_Mail_Id', models.CharField(max_length=100)),
                ('Student_Date_of_Birth', models.DateField(blank=True, null=True)),
                ('Identity_Card_Aadhar_Copy', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Students_data)),
                ('Student_Photo', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Students_data)),
                ('Course_Type', models.CharField(choices=[('Week Days', 'Week Days'), ('Week End', 'Week End')], max_length=20)),
                ('Payment_Type', models.CharField(choices=[('Full', 'Full'), ('Part', 'Part')], max_length=20)),
                ('Transaction_ID', models.IntegerField()),
                ('Account_Holder_Name', models.CharField(max_length=100)),
                ('Amount_Paide', models.FloatField(default=0)),
                ('Balance_Amount', models.FloatField(default=0)),
                ('Created_date', models.DateTimeField()),
                ('Updated_date', models.DateTimeField()),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_created_by', to='Inlingua_app.employees')),
                ('Language_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.language')),
                ('Level_and_Hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.levelsandhour')),
                ('Student_Counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.nameofcounselor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_updated_by', to='Inlingua_app.employees')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer_ID', models.CharField(default=Inlingua_app.models.generate_trainer_id, max_length=20, unique=True)),
                ('trainer_name', models.CharField(max_length=100)),
                ('trainer_dob', models.DateField()),
                ('trainer_education', models.CharField(max_length=100)),
                ('trainer_mail', models.EmailField(max_length=254)),
                ('trainer_phone', models.CharField(max_length=15)),
                ('trainer_languages', models.CharField(max_length=100)),
                ('trainer_address', models.TextField()),
                ('trainer_photo', models.ImageField(upload_to=Inlingua_app.models.Trainer_data)),
                ('trainer_bank_details', models.CharField(max_length=100)),
                ('trainer_aadhar', models.CharField(max_length=12)),
                ('trainer_role', models.CharField(max_length=100)),
                ('Created_date', models.DateTimeField()),
                ('Updated_date', models.DateTimeField()),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers_created_by', to='Inlingua_app.employees')),
                ('Updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainers_updated_by', to='Inlingua_app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year_of_passing', models.CharField(max_length=4)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inlingua_app.trainertable')),
            ],
        ),
    ]
