# Generated by Django 5.0.4 on 2024-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='Balance_Amount',
            field=models.FloatField(default=0),
        ),
    ]
