# Generated by Django 5.0.4 on 2024-07-29 10:17

import Inlingua_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0003_paymentreceipt_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_number',
            field=models.CharField(default=Inlingua_app.models.PaymentReceiptID, max_length=15, unique=True),
        ),
    ]
