# Generated by Django 4.2.13 on 2024-07-16 19:36

import Inlingua_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inlingua_app', '0007_trainer_table_remove_trainer_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.CharField(default=Inlingua_app.models.generate_employee_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('employee_photo', models.FileField(blank=True, null=True, upload_to=Inlingua_app.models.Employee_data)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_business_manager', models.BooleanField(default=False)),
                ('is_trainer_head', models.BooleanField(default=False)),
                ('is_trainer', models.BooleanField(default=False)),
                ('is_accoountant', models.BooleanField(default=False)),
                ('is_business_development_executive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
