# Generated by Django 4.2.13 on 2024-07-16 19:53

import Inlingua_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0008_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_table',
            name='employee_ID',
            field=models.CharField(default=Inlingua_app.models.generate_employee_id, max_length=20, unique=True),
        ),
    ]
