# Generated by Django 5.0.4 on 2024-07-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0011_alter_currentrole_current_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrole',
            name='current_role',
            field=models.CharField(max_length=30),
        ),
    ]
