# Generated by Django 5.0.4 on 2024-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0013_alter_employees_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrole',
            name='current_role',
            field=models.CharField(max_length=31),
        ),
    ]
