# Generated by Django 5.0.4 on 2024-07-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0015_employees_aadhar_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
