# Generated by Django 5.0.4 on 2024-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0016_alter_employees_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Created_by',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='Updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='Updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
