# Generated by Django 5.0.4 on 2024-07-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inlingua_app', '0017_employees_created_by_employees_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Created_by',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Created_date',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Updated_by',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Updated_date',
        ),
    ]
